---
name: Deploy to Docker Host

'on':
  workflow_run:
    workflows: ["Build and Push Docker Container"]
    types:
      - completed
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the docker-build workflow completed successfully
    # and actually pushed images (not just PR builds)
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event == 'push' ||
       (github.event.workflow_run.event == 'pull_request_target' &&
        github.event.workflow_run.head_branch == 'master'))

    steps:
      - name: Deploy to Docker Host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image from GHCR
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop and remove existing container if it exists
            docker stop graphhopper || true
            docker rm graphhopper || true

            # Run the new container
            docker run -d \
              --name graphhopper \
              -p 8989:8989 \
              --restart unless-stopped \
              ghcr.io/${{ github.repository }}:latest

            # Clean up old images to save space
            docker image prune -f
