name: Build and Push Docker Container

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  pull_request_target:
    types: [closed]
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    # Only run on pushes to master, or when PRs are merged to master
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request_target' &&
       github.event.pull_request.merged == true) ||
      github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up environment and security context
        run: |
          echo "Setting up Docker build environment"
          echo "REGISTRY=${{ env.REGISTRY }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "Configuring network settings for Docker operations"
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For pull_request_target, checkout the merge commit
          ref: |
            ${{
              github.event_name == 'pull_request_target' &&
              github.event.pull_request.merge_commit_sha || github.sha
            }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache node
        uses: actions/cache@v4
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web-bundle/node_modules
          key: |
            ${{ runner.os }}-node-${{
              hashFiles('**/pom.xml', '**/package.json')
            }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        # Push images only on master branch pushes or merged PRs
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'pull_request_target' &&
           github.event.pull_request.merged == true)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=master-,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-,enable=${{
              github.event_name != 'pull_request_target'
            }}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=GraphHopper
            org.opencontainers.image.description=GraphHopper routing engine
            org.opencontainers.image.vendor=GraphHopper

      - name: Validate Docker tags
        id: validate-tags
        run: |
          echo "Validating Docker tags for invalid reference format..."
          tags="${{ steps.meta.outputs.tags }}"
          invalid_tags=""
          valid_tags=""
          
          # Process each tag line by line
          while IFS= read -r tag; do
            # Skip empty lines
            if [[ -n "$tag" && "$tag" != " " ]]; then
              # Extract tag part after last colon
              tag_part="${tag##*:}"
              if [[ "$tag_part" =~ ^-.*$ ]]; then
                echo "❌ Invalid tag detected (starts with dash): $tag"
                if [[ -z "$invalid_tags" ]]; then
                  invalid_tags="$tag"
                else
                  invalid_tags="$invalid_tags"$'\n'"$tag"
                fi
              else
                echo "✅ Valid tag: $tag"
                if [[ -z "$valid_tags" ]]; then
                  valid_tags="$tag"
                else
                  valid_tags="$valid_tags"$'\n'"$tag"
                fi
              fi
            fi
          done <<< "$tags"
          
          # Set outputs for subsequent steps
          if [[ -n "$invalid_tags" ]]; then
            echo "has_invalid_tags=true" >> $GITHUB_OUTPUT
            echo "invalid_tags<<EOF" >> $GITHUB_OUTPUT
            echo "$invalid_tags" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_invalid_tags=false" >> $GITHUB_OUTPUT
          fi
          
          # Set valid tags output
          if [[ -n "$valid_tags" ]]; then
            echo "valid_tags<<EOF" >> $GITHUB_OUTPUT
            echo "$valid_tags" >> $GITHUB_OUTPUT  
            echo "EOF" >> $GITHUB_OUTPUT
            echo "has_valid_tags=true" >> $GITHUB_OUTPUT
          else
            echo "has_valid_tags=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        # Skip Docker build if we only have invalid tags (leading dash issue)
        if: steps.validate-tags.outputs.has_invalid_tags != 'true' || steps.validate-tags.outputs.has_valid_tags == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # Push only on master branch pushes or merged PRs
          push: |
            ${{
              github.event_name == 'push' ||
              (github.event_name == 'pull_request_target' &&
               github.event.pull_request.merged == true)
            }}
          tags: |
            ${{
              steps.validate-tags.outputs.has_valid_tags == 'true' &&
              steps.validate-tags.outputs.valid_tags ||
              steps.meta.outputs.tags
            }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Report Docker build skipped due to invalid tags
        if: steps.validate-tags.outputs.has_invalid_tags == 'true' && steps.validate-tags.outputs.has_valid_tags != 'true'
        run: |
          echo "⚠️ Docker build was skipped due to invalid tag format (tags starting with dash)."
          echo "This is a known issue with Docker tag naming conventions and does not indicate a build failure."
          echo ""
          echo "Invalid tags detected:"
          echo "${{ steps.validate-tags.outputs.invalid_tags }}"
          echo ""
          echo "The workflow will continue successfully as this is not a critical error."
