name: Trigger Benchmarks
on: push
jobs:
  trigger_measurement:
    if: github.repository_owner == 'graphhopper'
    runs-on: ubuntu-latest
    environment: benchmarks
    steps:
      - name: Set up environment for benchmarks
        run: |
          echo "Setting up benchmark trigger environment"
          echo "BENCHMARKS_ENABLED=true" >> $GITHUB_ENV
          echo "Configuring network settings for API calls"
      
      - name: trigger
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.BENCHMARKS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ secrets.BENCHMARKS_REPO }}/dispatches" \
          -d '{"event_type":"measurement_core","client_payload":{"core_commit": "'$GITHUB_SHA'", "core_branch": "${{ github.ref_name }}" }}'
